### ISSUE TITLE
Wrong p-value for CG sign-test

### ISSUE THREAD

**Issue by atecon** [atecon/FEP#22]
Hi @schreibe,

 I found a bug in the Campbell & Ghysels sign nonparam. statistics which starts here: https://github.com/atecon/FEP/blob/master/src/FEP_tests_individual.inp#L429

For a current project, I obtain p-values lager than 1 for the sign statistics which is computed here:
https://github.com/atecon/FEP/blob/master/src/FEP_tests_individual.inp#L503

```
if b.CGSIGNstat < (T + 1) / 2 # left tail of the distribution
        temp = pvalue(B, 0.5, T, b.CGSIGNstat)
        # (gretl does > x, not >= x here!)
        b.CGSIGNpval = 2 * (1 - temp) # because of symmetry under p=0.5
else	# right tail
        # (force X >= x by passing x' = x-1, since gretl does > x)
        b.CGSIGNpval = 2 * pvalue(B, 0.5, T, b.CGSIGNstat - 1)
        # (again, because of symmetry)
endif
```

In my example, I have `n=80` trials and a test statistics of 40. Using gretl's p-value finder via the GUI, I get:

> Binomial (p = 0.5, n = 80):
 Prob(x > 40) = 0.455536
 Prob(x <= 40) = 0.544464
 Prob(x >= 40) = 0.544464
 Prob(x = 40) = 0.0889279

However, doCGtest() returns p-value of 1.0889279. Here for replication locally:

```
temp = pvalue(B, 0.5, 80, 40)
pval = 2 * (1 - temp) # because of symmetry under p=0.5
print pval  #1.0889279

pval_sign_righttail = 2 * pvalue(B, 0.5, 80, 40 - 1)
print pval_sign_righttail # 1.0889279
```

I think what we actually want under the first if-condiction is:

~~~
scalar greater_than = pvalue(B, 0.5, 80, 40)
scalar equal_to_teststat = 1 - 2 * greater_than # because of symmetry under p=0.5
scalar geq = greater_than + equal_to_teststat

greater_than =  0.45553606
equal_to_teststat =  0.088927879
geq =  0.54446394
~~~

For the thing under the `else` keyword, I can't remember the details about the `-1` "correction" right now. But this part also needs being fixed.

Once, we have clarified this issue, I can implement the fix within the `bugfix/loadextra` branch for which already a pull-request exists.

**Comment by schreibe** [comment]
Ah, those stupid discrete distributions ;-)
First of all, "< (T + 1) / 2" doesn't really ensure the left tail, it could also include the center - as in your example, with T=80 (an even number) we have outcomes from 0...80, so 81 = T+1; and 40 is the 41st outcome, right in the middle, not part of the left tail. So I think this check needs to be simply "< T/2 ". This also works with odd T values, e.g. T=11, then this checks for "<6", which is correct.
Next, in the left tail we could simply use cdf() instead of pvalue(). So: "b.CGSIGNpval = 2 * cdf( B, 0.5, T, b.CGSIGNstat - 1)", the -1 being needed because with cdf() gretl does X<=x, not "<". 
About the right tail: the analog check should be ">  T/2 ". And yes, I think the -1 needs to be removed in this right tail with pvalue().
Finally, we need a new else branch which only covers the case that we're right in the middle, which can only happen with an even T, so the test stat would be just == T/2. But actually the formula would be the same as for the right tail (with the -1 removed), so we could also subsume it there.
Do you want me to do that, or are you going ahead with it?

**Comment by atecon** [comment]
> Ah, those stupid discrete distributions ;-)
Indeed!

> Do you want me to do that, or are you going ahead with it?

Thanks, good idea.
To make sure things align nicely, I suggest to merge the open pull-request first into master of everything is fine. Then you can create a new branch for this bugfix and start from current master.
